server:
  port: 9090

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpatest
    username: jpatest
    password: qwer1234!
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      maximum-pool-size: 20


  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #dialect: org.hibernate.dialect.MariaDBDialect
        #default_batch_fetch_size: 2


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql: trace
    org.springframework.jdbc.core: TRACE
    com.example: DEBUG
